### ISSUE TITLE
As a Marketing Coordinator, I want to receive an email once a students contribution is submitted. This will make me aware of what student’s have submitted work. Consequently, I will have to comment on submissions within 14 days. 

### ISSUE THREAD

**Issue by hennah-s** [GreenwichEWSD/Documentation#14]

**Comment by JoeScho** [comment]
Blocked by #18

**Comment by JoeScho** [comment]
This is completed - however, it does not work (I believe due to the university's firewall). I've added the same code to a project on my local machine and it works just fine... Something to ask ray about
![email](https://cloud.githubusercontent.com/assets/12475501/23589709/e621d5be-01c9-11e7-89fd-7e38a3eba211.png)
